require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CryptocurrencyApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'CryptocurrencyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CryptocurrencyApp-tvOS' do
  # Pods for CryptocurrencyApp-tvOS

  target 'CryptocurrencyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
